name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build pages
      run: npm run build
    - name: build
      run: npm run dist:linux
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist
          !dist/linux-unpacked
          !dist/win-unpacked
          !dist/mac

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build pages
      run: npm run build
    - name: build
      run: npm run dist:mac
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist
          !dist/linux-unpacked
          !dist/win-unpacked
          !dist/mac

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build pages
      run: npm run build
    - name: build
      run: npm run dist:win
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist
          !dist/linux-unpacked
          !dist/win-unpacked
          !dist/mac